<?xml version="1.0"?>
<robot name="diffbot_chassis" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find diffbot_description)/urdf/properties.xacro"/>
    <xacro:macro name="chassis" params="">
        <link name="base_footprint"/>

        <joint name="base_footprint_to_base_link" type="fixed">
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <origin rpy="0 0 0" xyz="0 0 0.1"/>
        </joint>

        <link name="base_link">
            <inertial>
                <origin rpy="0 0 0" xyz="${CHASSIS_COM}"/>
                <mass value="${CHASSIS_M}"/>
                <inertia ixx="${CHASSIS_ixx}" ixy="${CHASSIS_ixy}" ixz="${CHASSIS_ixz}"
                    iyy="${CHASSIS_iyy}" iyz="${CHASSIS_iyz}" izz="${CHASSIS_izz}"/>
            </inertial>
            <visual>
                <origin rpy="0 0 0" xyz="-0.1 0 0.05"/>
                <geometry>
                    <box size="0.6 ${WHEEL_SEPARATION-0.02} 0.15"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="-0.1 0 0.05"/>
                <geometry>
                    <box size="0.6 ${WHEEL_SEPARATION-0.02} 0.15"/>
                </geometry>
            </collision>
        </link>

        <joint name="base_link_to_upper" type="fixed">
            <parent link="base_link"/>
            <child link="upper"/>
            <origin rpy="0 0 0" xyz="0 0 0.175"/>
        </joint>

        <link name="upper">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <box size="0.3 0.3 0.10"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <box size="0.3 0.3 0.10"/>
                </geometry>
            </collision>
        </link>

        <joint name="base_link_to_caster" type="fixed">
            <parent link="base_link"/>
            <child link="caster"/>
            <origin rpy="0 0 0" xyz="-0.3 0 -0.05"/>
        </joint>

        <link name="caster">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <sphere radius="0.05"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <sphere radius="0.05"/>
                </geometry>
            </collision>
        </link>

        <joint name="camera_joint" type="fixed">
            <axis xyz="0 1 0" />
            <origin xyz="0.175 0 0.15" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="camera_link"/>
        </joint>

        <!-- Camera -->
        <link name="camera_link">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${camera_link} ${camera_link} ${camera_link}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${camera_link} ${camera_link} ${camera_link}"/>
                </geometry>
            </visual>

            <inertial>
                <mass value="1e-5" />
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
            </inertial>
        </link>

        <!-- camera -->
        <gazebo reference="camera_link">
            <sensor type="camera" name="camera1">
            <update_rate>30.0</update_rate>
            <camera name="head">
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                <width>800</width>
                <height>800</height>
                <format>R8G8B8</format>
                </image>
                <clip>
                <near>0.02</near>
                <far>300</far>
                </clip>
                <noise>
                <type>gaussian</type>
                <!-- Noise is sampled independently per pixel on each frame.
                    That pixel's noise value is added to each of its color
                    channels, which at that point lie in the range [0,1]. -->
                <mean>0.0</mean>
                <stddev>0.007</stddev>
                </noise>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>0.0</updateRate>
                <cameraName>rrbot/camera1</cameraName>
                <imageTopicName>image_raw</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <frameName>camera_link</frameName>
                <hackBaseline>0.07</hackBaseline>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
            </plugin>
            </sensor>
        </gazebo>

        <joint name="hokuyo_joint" type="fixed">
            <axis xyz="0 1 0" />
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
            <parent link="upper"/>
            <child link="hokuyo_link"/>
        </joint>

        <!-- Hokuyo Laser -->
        <link name="hokuyo_link">
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.1 0.1 0.1"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="0.1 0.1 0.1"/>
                </geometry>
            </visual>

            <inertial>
                <mass value="1e-5" />
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
            </inertial>
        </link>

        <!-- hokuyo -->
        <gazebo reference="hokuyo_link">
            <sensor type="ray" name="head_hokuyo_sensor">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>40</update_rate>
            <ray>
                <scan>
                <horizontal>
                    <samples>720</samples>
                    <resolution>1</resolution>
                    <min_angle>-1.570796</min_angle>
                    <max_angle>1.570796</max_angle>
                </horizontal>
                </scan>
                <range>
                <min>0.10</min>
                <max>30.0</max>
                <resolution>0.01</resolution>
                </range>
                <noise>
                <type>gaussian</type>
                <!-- Noise parameters based on published spec for Hokuyo laser
                    achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
                    stddev of 0.01m will put 99.7% of samples within 0.03m of the true
                    reading. -->
                <mean>0.0</mean>
                <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
                <topicName>/rrbot/laser/scan</topicName>
                <frameName>hokuyo_link</frameName>
            </plugin>
            </sensor>
        </gazebo>

        <gazebo reference="base_link">
            <mu1>0</mu1>
            <mu2>0</mu2>
            <material>Gazebo/Gold</material>
        </gazebo>

        <gazebo reference="upper">
            <mu1>0</mu1>
            <mu2>0</mu2>
            <material>Gazebo/Gold</material>
        </gazebo>

        <gazebo reference="caster">
            <mu1>0</mu1>
            <mu2>0</mu2>
            <material>Gazebo/Yellow</material>
        </gazebo>

        <gazebo reference="camera_link">
            <mu1>0</mu1>
            <mu2>0</mu2>
            <material>Gazebo/Yellow</material>
        </gazebo>

        <gazebo reference="hokuyo_link">
            <mu1>0</mu1>
            <mu2>0</mu2>
            <material>Gazebo/Yellow</material>
        </gazebo>

    </xacro:macro>

</robot>